AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'app/views/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/blockchain_pb.rb'
    - 'tmp/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 55

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 20

Naming/MemoizedInstanceVariableName:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    find_all: 'select'

Style/DoubleNegation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'

Style/ClassAndModuleChildren:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 25
  ExcludedMethods:
    - refine
    - included

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false
