version: '3'
services:
  app: &app_base
    image: data_ouyeel_platform_app:latest
    volumes:
      - .:/app
    command: bundle exec puma -C config/puma.docker.rb
    # environment:
    #   - RAILS_LOG_TO_STDOUT=1 # 设置即可标准输出
    #   - DB_HOST=192.168.1.77
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=adminpassword
    #   - DB_NAME_PRO=ouyeel_storage_production
    #   - REDIS_URL=redis://192.168.1.70:6379/0
    #   - CITA_URL=http://node1:1337/
    #   - DB_POOL=25
    depends_on:
      - db
      - redis

  sync:
    <<: *app_base
    command: bundle exec rails daemons:sync:start

  sidekiq:
    <<: *app_base
    command: bundle exec sidekiq -C config/sidekiq.yml
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: data_ouyeel_platform_web:latest
    depends_on:
      - app
    ports:
      - 8888:80

  redis:
    image: redis:5.0.1
    volumes:
      - ./docker/redis:/data

  db:
    image: postgres:10.5
    volumes:
      - ./docker/data:/var/lib/postgresql/data
